<?php

/**
 * @file
 * Contains ec_payment_free.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 */
function ec_payment_free_commerce_checkout_pane_info_alter(&$panes): void {
  if (isset($panes['payment_information'])) {
    $panes['payment_information']['class'] = 'Drupal\ec_payment_free\Plugin\Commerce\CheckoutPane\FreePaymentInformation';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ec_payment_free_form_commerce_checkout_flow_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $form['#validate'][] = 'ec_payment_free_checkout_validate';
}

/**
 * Validation handler to clear billing errors for free payment.
 */
function ec_payment_free_checkout_validate(&$form, FormStateInterface $form_state): void {
  $payment_helper = \Drupal::service('ec_payment_free.helper');
  $value = $form_state->getValue(['payment_information', 'payment_method']);
  if (empty($value)) {
    return;
  }

  $plugin_id = $payment_helper->getGatewayPaymentPluginId($value);
  if ($payment_helper->isFreePayment($plugin_id)) {
    return;
  }

  // Clear billing/address/profile validation errors.
  $errors = $form_state->getErrors();
  if (empty($errors)) {
    return;
  }

  $form_state->clearErrors();
  foreach ($errors as $field => $error) {
    if (!preg_match('/(billing|address|profile)/', $field)) {
      $form_state->setErrorByName($field, $error);
    }
  }

}
